In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("E:\\xiongan\\pixel_info.csv")

In [4]:
df.__len__()

3677110

In [26]:
x,y,_,_ = df.loc[0]

In [30]:
type(df.loc[0])

pandas.core.series.Series

In [5]:
import spectral
import torch
import torch.nn as nn

In [6]:
lstm = nn.LSTM(input_size=1, 
                hidden_size=16, 
                batch_first=True, 
                num_layers=2,
                dropout=0.1,
                bidirectional=True,
                recurrent_initializer='orthogonal')

In [9]:
list(lstm.w)

[[Parameter containing:
  tensor([[-0.0057],
          [ 0.1442],
          [ 0.1930],
          [-0.1722],
          [ 0.0900],
          [-0.2041],
          [-0.2405],
          [-0.1193],
          [-0.1416],
          [ 0.1401],
          [ 0.0099],
          [-0.2471],
          [ 0.1983],
          [ 0.1767],
          [ 0.0157],
          [ 0.0798],
          [-0.1661],
          [ 0.0583],
          [-0.1566],
          [-0.1312],
          [ 0.2256],
          [ 0.2461],
          [ 0.0020],
          [ 0.1632],
          [-0.2188],
          [-0.0481],
          [ 0.0893],
          [ 0.0517],
          [ 0.1375],
          [ 0.1351],
          [-0.1780],
          [-0.2062],
          [ 0.1462],
          [-0.1514],
          [-0.1142],
          [ 0.1824],
          [-0.1266],
          [ 0.1846],
          [-0.0581],
          [-0.0245],
          [ 0.0340],
          [ 0.2094],
          [ 0.1960],
          [-0.1030],
          [-0.2337],
          [ 0.2364],
          

In [13]:
h[-1,:,:].shape

torch.Size([1, 16])

In [14]:
torch.cat((h[-1,:,:], h[-2,:,:]), 1).shape

torch.Size([1, 32])

In [2]:
img = spectral.envi.open("E:\\xiongan\\XiongAn.hdr")

In [4]:
img[0,0]/6000

array([0.2175    , 0.20916667, 0.22016667, 0.2295    , 0.23366667,
       0.24433333, 0.25616667, 0.251     , 0.2715    , 0.2735    ,
       0.28083333, 0.293     , 0.27416667, 0.29283333, 0.30616667,
       0.31116667, 0.331     , 0.33533333, 0.3485    , 0.35416667,
       0.36333333, 0.36883333, 0.37216667, 0.37816667, 0.38733333,
       0.387     , 0.3885    , 0.39666667, 0.403     , 0.403     ,
       0.39633333, 0.4055    , 0.41966667, 0.4265    , 0.43216667,
       0.42      , 0.42516667, 0.433     , 0.43033333, 0.44716667,
       0.4475    , 0.45566667, 0.4515    , 0.46566667, 0.46833333,
       0.478     , 0.47916667, 0.48333333, 0.47366667, 0.486     ,
       0.4855    , 0.49033333, 0.506     , 0.49566667, 0.51933333,
       0.51433333, 0.52366667, 0.52016667, 0.5185    , 0.53816667,
       0.54166667, 0.54133333, 0.54166667, 0.55783333, 0.54766667,
       0.54916667, 0.5575    , 0.55966667, 0.5725    , 0.57016667,
       0.577     , 0.58283333, 0.57183333, 0.5785    , 0.5795 

In [31]:
torch.Tensor(img.asarray()[0,0]/6000)

tensor([0.2175, 0.2092, 0.2202, 0.2295, 0.2337, 0.2443, 0.2562, 0.2510, 0.2715,
        0.2735, 0.2808, 0.2930, 0.2742, 0.2928, 0.3062, 0.3112, 0.3310, 0.3353,
        0.3485, 0.3542, 0.3633, 0.3688, 0.3722, 0.3782, 0.3873, 0.3870, 0.3885,
        0.3967, 0.4030, 0.4030, 0.3963, 0.4055, 0.4197, 0.4265, 0.4322, 0.4200,
        0.4252, 0.4330, 0.4303, 0.4472, 0.4475, 0.4557, 0.4515, 0.4657, 0.4683,
        0.4780, 0.4792, 0.4833, 0.4737, 0.4860, 0.4855, 0.4903, 0.5060, 0.4957,
        0.5193, 0.5143, 0.5237, 0.5202, 0.5185, 0.5382, 0.5417, 0.5413, 0.5417,
        0.5578, 0.5477, 0.5492, 0.5575, 0.5597, 0.5725, 0.5702, 0.5770, 0.5828,
        0.5718, 0.5785, 0.5795, 0.5778, 0.5762, 0.5880, 0.5898, 0.5880, 0.5890,
        0.5705, 0.5947, 0.5978, 0.6000, 0.6078, 0.6092, 0.6093, 0.6060, 0.6010,
        0.6030, 0.5933, 0.6073, 0.6075, 0.6045, 0.6035, 0.6115, 0.6080, 0.6012,
        0.5970, 0.6062, 0.6122, 0.6223, 0.6045, 0.6032, 0.5848, 0.5893, 0.5785,
        0.5767, 0.5730, 0.5740, 0.5628, 

In [1]:
import spectral
import torch
import torch.nn as nn
from torch.nn.functional import pad

In [9]:
class multi_scale_smoothing(nn.Module):
    def __init__(self, scale=8):
        super().__init__()
        self.scale = scale
        self.front = 7
    
    def forward(self, x):
        b, l = x.shape
        front = self.scale-1
        x = pad(x, (front,front), mode='replicate')
        result = torch.zeros(b,l,self.scale)
        for i in range(l):
            for j in range(self.scale):
                result[:,i,j] = torch.mean(x[:,i+front-j:i+front+j+1], dim=1)
        return result

In [2]:
a = torch.Tensor([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])

In [14]:
ss = multi_scale_smoothing(5)

In [15]:
ss(a)[0]

tensor([[1.0000, 1.3333, 1.6000, 1.8571, 2.1111],
        [2.0000, 2.0000, 2.2000, 2.4286, 2.5556],
        [3.0000, 3.0000, 3.0000, 3.0000, 3.0000],
        [4.0000, 4.0000, 3.8000, 3.5714, 3.4444],
        [5.0000, 4.6667, 4.4000, 4.1429, 3.8889]])

In [11]:
pad(a,(5,5),mode='replicate')

tensor([[1., 1., 1., 1., 1., 1., 2., 3., 4., 5., 5., 5., 5., 5., 5.],
        [1., 1., 1., 1., 1., 1., 2., 3., 4., 5., 5., 5., 5., 5., 5.],
        [1., 1., 1., 1., 1., 1., 2., 3., 4., 5., 5., 5., 5., 5., 5.],
        [1., 1., 1., 1., 1., 1., 2., 3., 4., 5., 5., 5., 5., 5., 5.],
        [1., 1., 1., 1., 1., 1., 2., 3., 4., 5., 5., 5., 5., 5., 5.]])

In [4]:
torch.cat((torch.zeros(5,1),a),1)

tensor([[0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.]])

In [14]:
for i in range(0,5):
    print(i)

0
1
2
3
4
